[package]
name = "cmz_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
cmz_core = { path = "../cmz_core" }
syn = { version = "2.0", features = ["extra-traits", "visit-mut"] }
quote = "1.0"
darling = "0.20"
proc-macro2 = "1.0"
